# Autogenerated justfile by Python script
# Timestamp: 2025-06-02T15:00:41.991145
# Logic: Generates 'play-[id]' if 'play' is in id (case-insensitive), otherwise 'train-[id]'.
# Searched in: /home/gonzales/Documents/repositories/sematron_rl_workshop_2025/isaaclab_experiments
list_envs:
   python scripts/list_envs.py --/log/level=error --/log/fileLogLevel=error --/log/outputStreamLevel=error

generate_envs:
   python scripts/generate_justfile.py

# Recipes from: isaaclab_experiments/go1_low_level/__init__.py
train-Go1-LowLevel-Unitree-v0:
    python scripts/train_rsl.py --task "Go1-LowLevel-Unitree-v0" --headless

play-Go1-LowLevel-Unitree-Play-v0:
    python scripts/play.py --task "Go1-LowLevel-Unitree-Play-v0"
