# Autogenerated justfile by Python script
# Timestamp: 2025-05-30T11:58:49.315069
# Logic: Generates 'play-[id]' if 'play' is in id (case-insensitive), otherwise 'train-[id]'.
# Searched in: /home/gonzales/Documents/repositories/isaaclab-experiments/isaaclab_experiments
list_envs:
   python scripts/list_envs.py --/log/level=error --/log/fileLogLevel=error --/log/outputStreamLevel=error

generate_envs:
   python scripts/generate_justfile.py

# Recipes from: isaaclab_experiments/go1_flat_deploy/__init__.py
train-Go1-Velocity-Flat-Unitree-Go1-v0:
    python scripts/train_rsl.py --task "Go1-Velocity-Flat-Unitree-Go1-v0" --headless

# Recipes from: isaaclab_experiments/b2_low_level/__init__.py
train-B2-LowLevel-Unitree-v0:
    python scripts/train_rsl.py --task "B2-LowLevel-Unitree-v0" --headless

play-B2-LowLevel-Unitree-Play-v0:
    python scripts/play.py --task "B2-LowLevel-Unitree-Play-v0"

train-B2-LowLevel-Unitree-Flat-v0:
    python scripts/train_rsl.py --task "B2-LowLevel-Unitree-Flat-v0" --headless

play-B2-LowLevel-Unitree-Flat-Play-v0:
    python scripts/play.py --task "B2-LowLevel-Unitree-Flat-Play-v0"

# Recipes from: isaaclab_experiments/spot_manipulation/__init__.py
train-Spot-Manipulation:
    python scripts/train_rsl.py --task "Spot-Manipulation" --headless

play-Spot-Manipulation-Play:
    python scripts/play.py --task "Spot-Manipulation-Play"

# Recipes from: isaaclab_experiments/go1_low_level/__init__.py
train-Go1-LowLevel-Unitree-v0:
    python scripts/train_rsl.py --task "Go1-LowLevel-Unitree-v0" --headless

play-Go1-LowLevel-Unitree-Play-v0:
    python scripts/play.py --task "Go1-LowLevel-Unitree-Play-v0"

# Recipes from: isaaclab_experiments/anymal_flat_deploy/__init__.py
train-Custom-Velocity-Flat-Anymal-C-Direct-v0:
    python scripts/train_rsl.py --task "Custom-Velocity-Flat-Anymal-C-Direct-v0" --headless

# Recipes from: isaaclab_experiments/go1_navigation/__init__.py
train-Go1-Navigation-v0:
    python scripts/train_rsl.py --task "Go1-Navigation-v0" --headless

play-Go1-Navigation-Play-v0:
    python scripts/play.py --task "Go1-Navigation-Play-v0"

# Recipes from: isaaclab_experiments/go1_navigation_flat/__init__.py
train-Isaac-Navigation-Flat-Go1-v0:
    python scripts/train_rsl.py --task "Isaac-Navigation-Flat-Go1-v0" --headless

play-Isaac-Navigation-Flat-Go1-Play-v0:
    python scripts/play.py --task "Isaac-Navigation-Flat-Go1-Play-v0"

# Recipes from: isaaclab_experiments/spot_low_level/__init__.py
train-Spot-LowLevel-v0:
    python scripts/train_rsl.py --task "Spot-LowLevel-v0" --headless

play-Spot-LowLevel-Play-v0:
    python scripts/play.py --task "Spot-LowLevel-Play-v0"

train-Spot-LowLevel-Flat-v0:
    python scripts/train_rsl.py --task "Spot-LowLevel-Flat-v0" --headless

play-Spot-LowLevel-Flat-Play-v0:
    python scripts/play.py --task "Spot-LowLevel-Flat-Play-v0"
