#!/bin/bash

# Script to autogenerate a justfile with train or play recipes
# based on gym.register IDs in __init__.py files.
# If ID contains "play", only a play recipe is generated.
# Otherwise, only a train recipe is generated.

# Define the directory to search for __init__.py files
SEARCH_DIR="isaaclab_experiments"
# Define the output justfile name
JUSTFILE="justfile"

# Ensure the search directory exists
if [ ! -d "$SEARCH_DIR" ]; then
  echo "Error: Directory '$SEARCH_DIR' not found."
  exit 1
fi

echo "# Autogenerated justfile" >"$JUSTFILE"
echo "# Timestamp: $(date)" >>"$JUSTFILE"
echo "# Logic: Generates 'play-[id]' if 'play' is in id, otherwise 'train-[id]'." >>"$JUSTFILE"
echo "" >>"$JUSTFILE"

# Find all __init__.py files and process them
find "$SEARCH_DIR" -name "__init__.py" -print0 | while IFS= read -r -d $'\0' init_file; do
  echo "# Recipes from: $init_file" >>"$JUSTFILE"
  # Extract IDs using grep and sed
  # This regex looks for 'id=' followed by a quoted string, capturing the string content.
  # It handles both single and double quotes.
  grep -Eo 'id\s*=\s*["'\''].*?["'\'']' "$init_file" | sed -E 's/id\s*=\s*["'\''](.*?)["'\'']/\1/' | while IFS= read -r task_id; do
    if [ -n "$task_id" ]; then
      echo "Found ID: $task_id"

      # Convert task_id to lowercase for case-insensitive check
      task_id_lower=$(echo "$task_id" | tr '[:upper:]' '[:lower:]')

      if [[ "$task_id_lower" == *play* ]]; then
        # Generate only play recipe
        echo "play-$task_id:" >>"$JUSTFILE"
        echo "    python scripts/play.py --task \"$task_id\"" >>"$JUSTFILE"
        echo "" >>"$JUSTFILE"
      else
        # Generate only train recipe
        echo "train-$task_id:" >>"$JUSTFILE"
        echo "    python scripts/train_rsl.py --task \"$task_id\" --headless" >>"$JUSTFILE"
        echo "" >>"$JUSTFILE"
      fi
    fi
  done
done

echo "Justfile '$JUSTFILE' generated successfully with conditional train/play recipes."
